### ISSUE TITLE
[Design-OLD] Wallet Service Authentication

### ISSUE THREAD

**Issue by natancamargo** [HathorNetwork/hathor-wallet-service-old#59]
# Motivation
Hathor Wallet Service needs an authentication mechanism. This authentication mechanism should support or at least consider session management for future improvements.

# Solution
## POST /login to generate a token
<img width="525" alt="image" src="https://user-images.githubusercontent.com/5104565/114062690-2d5fa700-986e-11eb-896c-25c0c5f4f488.png">

The purpose of this endpoint is to generate a token to be used later on every request to the API. 

It receives the following body parameters:
```ts
{
    "xpubkey": string,
    "timestamp": number,
    "signature": string,
}
```
To be valid, the signature should have been done to a message with `timestamp` and `xpubkey` concatenated using an `xprivkey` derivated on the path `m/1/1`.
The function that does this is:
```js
import bitcoreLib from "bitcore-lib";
import Message from "bitcore-message";

const verifySignature = (
  signature: string,
  xpubkey: string,
  timestamp: number
): boolean => {
  const message = String(timestamp).concat(xpubkey);
  const derivedXpubkey = new bitcoreLib.HDPublicKey(xpubkey).derive("m/1/1");
  const address = derivedXpubkey.publicKey.toAddress().toString();
  return new Message(message).verify(address, signature);
};
```

Currently, it generates a JWT token carrying:
```ts
{
    "xpubkey": string,
    "timestamp": number,
    "signature": string,
}
```

To generate such body params something like below can be done:
```js
const bitcoreLib = require("bitcore-lib");
const Message = require("bitcore-message");

const timestamp = Math.floor(Date.now() / 1000);
const xprivkey = new bitcoreLib.HDPrivateKey(
  "xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBxrMPHi"
);
const derivedPrivateKey = xprivkey.derive("m/1/1");
const xpubkey = xprivkey.hdPublicKey;
const message = String(timestamp).concat(xpubkey);
const signature = new Message(message).sign(derivedPrivateKey.privateKey);

console.info(
  JSON.stringify(
    {
      timestamp,
      xpub: xpubkey.toString(),
      signature: signature.toString(),
    },
    null,
    4
  )
);
```

## Authorizer (intercepts all requests to the API)
<img width="829" alt="image" src="https://user-images.githubusercontent.com/5104565/114062771-45372b00-986e-11eb-898c-3ddfe57630ad.png">

Basically, API Gateway calls the authorizer lambda to generate a policy allowing or not the request to the protected endpoints.
Currently, the authorizer decodes the JWT (carried by the Header "Authorization") to check the signature and the expiration time.

# Open discussions
1. **Does the AWS Authorizer add another lambda call which implies a higher cost and response delay?**
Yes, but I'm investigating if the token can be cached on the API Gateway itself to mitigate this issue. Some info about it [here](https://www.alexdebrie.com/posts/lambda-custom-authorizers/#caching-your-custom-authorizers).

2. **How can we make the authentication stateful to allow more sophisticated features that depend on session management?**
Under investigation.

3. **New dependency `bitcore-message` and the multiples instances of `bitcore-lib`.**
To solve this, package.json must declare a resolution to a `bitcore-lib` version (the same as the `hathor-wallet-lib`):
```json
...
  "resolutions": {
    "bitcore-lib": "0.16.0"
  }
...
```
Besides that, to enforce this resolution I'm using `npx npm-force-resolutions`, which is not the best solution. Better ways to do it are under investigation.

**Comment by r4mmer** [comment]
# Summary
[summary]: #summary

When calling a function from the wallet service the user can/must (depending on the function) provide some sort of authentication,
proving he has the private key of some resource the function is trying to access.
Eventually this could support session management for future improvements.
This design is for the service that will authenticate the user and authorize his access to the wallet service resources.

# Motivation
[motivation]: #motivation

Hathor Wallet Service needs an authentication (authn) and authorization (authz) mechanisms.

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

To make an authenticated call you need to provide a way for the service to verify that you have the private key associated with the wallet being accessed.
A way to authenticate is provide:

- A message
- The xpubkey
- The message signed by the private key

This way you could get the address from the xpubkey and validate that the message was signed with the private key of the address
Now, we can choose the message as a concatenation of available information, this way, anyone can build the original message and we can omit it from the required information.

```js
const xpubkey = "xxx";
const timestamp = 123;

const message = String(timestamp).concat(xpubkey);
```
Now to create the token we will be using the [simple-jwt](https://github.com/hokaccha/node-jwt-simple) lib.
This allows us to easily create a JWT token without dealing with some requirements of full jwt implementations.
```js
const jwt = require('jwt-simple');

// secret to sign jwt
const secret = "XXX";
// The info needed
const data = {
    ts: 123,
    xpub: "xxx",
    sign: "sss",
}

const token = jwt.encode(data, secret);
```
Now that we have a way to create a token, we need to understand what will be signed.
```js
const jwt = require('jwt-simple');
const bitcoreLib = require("bitcore-lib");
const Message = require("./bitcore-message");

const hdprivkey = "xprv9s21ZrQH143K3e6DUVMPzeKHiiQPiyRNy2QTpvCTB8XYTL7vWAj6BRXmp8NW4ovQvDTemNnNyArVeJTKetWFfcTLgPQJangAt3pkp7wLGNS"
const secret = "xxx";

const timestamp = Math.floor(Date.now() / 1000);
const xprivkey = new bitcoreLib.HDPrivateKey(hdprivkey);
const derivedPrivateKey = xprivkey.deriveChild("m/1/1");
const xpubkey = xprivkey.hdPublicKey;
const address = derivedPrivateKey.publicKey.toAddress().toString();
const message = String(timestamp).concat(address);
const signature = new Message(message).sign(derivedPrivateKey.privateKey);

const data = {
    ts: timestamp,
    xpub: xpubkey.toString(),
    sign: signature.toString(),
};
const token = jwt.encode(data, secret);
```
Now to verify the generated token:
```js
const Message = require("./bitcore-message");
const jwt = require('jwt-simple');

const token = '...'
const data = jwt.decode(token, secret);
const xpubkey = new bitcoreLib.HDPublicKey(data.xpub);
const address = xpubkey.deriveChild("m/1/1").publicKey.toAddress().toString()
const message = String(data.ts).concat(address);
const valid = new Message(message).verify(address, data.sign);
```
The endpoints needed are:
- /token
    * post data to generate token with secret
- /verify
    * post token to open the token with the secret and verify signature

Only these 2 endpoints need to know the secret, or the secret could be public and we could generate the token on the client and only have the verify endpoint.

Since current deployment of the wallet service is made in aws lambda with AWS API Gateway we will use a lambda authorizer as described [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html).
We will use response format version 2.0 described in the [lambda authorizer doc](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html) for simplicity.
The identity source will be the header Authorization and caching will be used.

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

### POST /token

This is a public endpoint that validates and exchanges a set of data to a token
Input JSON body:
```ts
{
    "ts": number,
    "xpub": string,
    "sign": string,
}
```
Return JSON body:
```ts
{
    "token": string
}
```

### Lambda authorizer (/verify)

This function will serve to validate the token given to the client proving he owns the wallet identified by `xpub`.
Input JSON body:
```ts
{
    "token": string
}
```
Return JSON body:
```ts
{
    "isAuthorized": boolean,
    "context": object,
}
```

### API Gateway

The routes that need authorization will be protected with the `verify` lambda authorizer.
If the header `Authorization` is not present, the API Gateway returns a HTTP 401 response,
The client then should create a token using the `token` endpoint and retry the call.

Caching the authorizer response is desirable because if would reduce number of calls to the lambda authorizer.

**Comment by r4mmer** [comment]
The design of this feature was moved to [#66](https://github.com/HathorNetwork/hathor-wallet-service/issues/66)
